name: Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Get commit count
      id: commit-count
      run: echo "::set-output name=COUNT::$(git rev-list --count HEAD)"

    - name: Build Docker image
      run: docker build -t aftab2010/gradient-website:v${{ steps.commit-count.outputs.COUNT }} .

    - name: Push Docker image to Docker Hub
      run: docker push aftab2010/gradient-website:v${{ steps.commit-count.outputs.COUNT }}